# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-03 12:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20170803_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0, 2400)),
        ),
    ]
