# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-14 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20170803_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='date_published',
            field=models.DateField(),
        ),
    ]
