# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-14 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20170814_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.IntegerField(default='999999999', null=True),
        ),
    ]
